package click

// Format is ClickHouse input/output format. The value is its string ID.
// User can construct custom formats by converting string to type Format.
// See https://clickhouse.com/docs/interfaces/formats
type Format string

// All output-able formats. Those cannot be used as output formats are not listed.
// See type Format for more info.
const (
	FormatTabSeparated                               Format = "TabSeparated"
	FormatTabSeparatedRaw                            Format = "TabSeparatedRaw"
	FormatTabSeparatedWithNames                      Format = "TabSeparatedWithNames"
	FormatTabSeparatedWithNamesAndTypes              Format = "TabSeparatedWithNamesAndTypes"
	FormatTabSeparatedRawWithNames                   Format = "TabSeparatedRawWithNames"
	FormatTabSeparatedRawWithNamesAndTypes           Format = "TabSeparatedRawWithNamesAndTypes"
	FormatTemplate                                   Format = "Template"
	FormatCSV                                        Format = "CSV"
	FormatCSVWithNames                               Format = "CSVWithNames"
	FormatCSVWithNamesAndTypes                       Format = "CSVWithNamesAndTypes"
	FormatCustomSeparated                            Format = "CustomSeparated"
	FormatCustomSeparatedWithNames                   Format = "CustomSeparatedWithNames"
	FormatCustomSeparatedWithNamesAndTypes           Format = "CustomSeparatedWithNamesAndTypes"
	FormatSQLInsert                                  Format = "SQLInsert"
	FormatValues                                     Format = "Values"
	FormatVertical                                   Format = "Vertical"
	FormatJSON                                       Format = "JSON"
	FormatJSONStrings                                Format = "JSONStrings"
	FormatJSONColumns                                Format = "JSONColumns"
	FormatJSONColumnsWithMetadata                    Format = "JSONColumnsWithMetadata"
	FormatJSONCompact                                Format = "JSONCompact"
	FormatJSONCompactStrings                         Format = "JSONCompactStrings"
	FormatJSONCompactColumns                         Format = "JSONCompactColumns"
	FormatJSONEachRow                                Format = "JSONEachRow"
	FormatPrettyJSONEachRow                          Format = "PrettyJSONEachRow"
	FormatJSONEachRowWithProgress                    Format = "JSONEachRowWithProgress"
	FormatJSONStringsEachRow                         Format = "JSONStringsEachRow"
	FormatJSONStringsEachRowWithProgress             Format = "JSONStringsEachRowWithProgress"
	FormatJSONCompactEachRow                         Format = "JSONCompactEachRow"
	FormatJSONCompactEachRowWithNames                Format = "JSONCompactEachRowWithNames"
	FormatJSONCompactEachRowWithNamesAndTypes        Format = "JSONCompactEachRowWithNamesAndTypes"
	FormatJSONCompactEachRowWithProgress             Format = "JSONCompactEachRowWithProgress"
	FormatJSONCompactStringsEachRow                  Format = "JSONCompactStringsEachRow"
	FormatJSONCompactStringsEachRowWithNames         Format = "JSONCompactStringsEachRowWithNames"
	FormatJSONCompactStringsEachRowWithNamesAndTypes Format = "JSONCompactStringsEachRowWithNamesAndTypes"
	FormatJSONCompactStringsEachRowWithProgress      Format = "JSONCompactStringsEachRowWithProgress"
	FormatJSONObjectEachRow                          Format = "JSONObjectEachRow"
	FormatBSONEachRow                                Format = "BSONEachRow"
	FormatTSKV                                       Format = "TSKV"
	FormatPretty                                     Format = "Pretty"
	FormatPrettyNoEscapes                            Format = "PrettyNoEscapes"
	FormatPrettyMonoBlock                            Format = "PrettyMonoBlock"
	FormatPrettyNoEscapesMonoBlock                   Format = "PrettyNoEscapesMonoBlock"
	FormatPrettyCompact                              Format = "PrettyCompact"
	FormatPrettyCompactNoEscapes                     Format = "PrettyCompactNoEscapes"
	FormatPrettyCompactMonoBlock                     Format = "PrettyCompactMonoBlock"
	FormatPrettyCompactNoEscapesMonoBlock            Format = "PrettyCompactNoEscapesMonoBlock"
	FormatPrettySpace                                Format = "PrettySpace"
	FormatPrettySpaceNoEscapes                       Format = "PrettySpaceNoEscapes"
	FormatPrettySpaceMonoBlock                       Format = "PrettySpaceMonoBlock"
	FormatPrettySpaceNoEscapesMonoBlock              Format = "PrettySpaceNoEscapesMonoBlock"
	FormatPrometheus                                 Format = "Prometheus"
	FormatProtobuf                                   Format = "Protobuf"
	FormatProtobufSingle                             Format = "ProtobufSingle"
	FormatProtobufList                               Format = "ProtobufList"
	FormatAvro                                       Format = "Avro"
	FormatParquet                                    Format = "Parquet"
	FormatArrow                                      Format = "Arrow"
	FormatArrowStream                                Format = "ArrowStream"
	FormatORC                                        Format = "ORC"
	FormatNpy                                        Format = "Npy"
	FormatRowBinary                                  Format = "RowBinary"
	FormatRowBinaryWithNames                         Format = "RowBinaryWithNames"
	FormatRowBinaryWithNamesAndTypes                 Format = "RowBinaryWithNamesAndTypes"
	FormatNative                                     Format = "Native"
	FormatNull                                       Format = "Null"
	FormatXML                                        Format = "XML"
	FormatCapnProto                                  Format = "CapnProto"
	FormatLineAsString                               Format = "LineAsString"
	FormatRawBLOB                                    Format = "RawBLOB"
	FormatMsgPack                                    Format = "MsgPack"
	FormatMarkdown                                   Format = "Markdown"
)
